### ISSUE TITLE
support for dualsense edge

### ISSUE THREAD

**Issue by Howarddj** [ugjka/ds360go#1]
any way to support dualsense edge?
Product ID is different so controller does not get recognised

Dualsense edge 30th anniversay edition - Vendor: 054c Product: 0df2

**Comment by Howarddj** [comment]
UPDATE: 

got it working by changing PID in source and rebuilding. 

maybe there is a way to rewrite the source so it could be used with various VID and PID?

**Comment by ugjka** [comment]
I'll rewrite stuff, thanks for letting me know

**Comment by ugjka** [comment]
Can you check the dev branch: https://github.com/ugjka/ds360go/tree/1-support-for-dualsense-edge

Commit: 39c1661

**Comment by Howarddj** [comment]
just cloned the new branch and rebuilt, all seems to be working.

thanks!
